<div class="container">
<h1>Madame Montcomery and The Cheshire CatHouse</h1><br>
<h3>What's Down this Rabbit Hole?</h3>

<p>Madame Montcomery's Cheshire CatHouse is a SteamPunk-influenced Original Interactive Experience. Comedy and Tradgedy each have their part, occasionally crossing into the other's territory in a story arch chronicalling the happenings around this disturbing and distorted, twisted, Alice in Wasteland style House of Joy affectionately named The Cheshire CatHouse.</p>

<h4>Characters:</h4><br><br>
<h5>Mr. Beaux Jangles</h5> <span class="tagline">(With the Thang he Dangles)</span><br> <p> - The "thang" in question is a pocket watch of mesmerizing nature. We know he's not the devil, The devil get's sympathy. You know those things you "wouldn't wish on your worst enemy?" You can wish them on him and still keep that promise. He has a swagger unmatched by man nor god. For a man that does the most underhanded things that make you want to kill him when he's not in front of you, he sure gets along with everyone in proximity. Never met someone so cold and so popular. </p>

<h5>Mrs. Montgomery</h5> <span class="tagline">(Hell, CEO)</span><br> <p> - Rumor has it she refused to move so they had to build hell around her. Jangles may own the business, but there's no question as to who runs it. Once it was built she realized she was confined to that small portion of it and came the the same sane and rational conclusion any of us would have... That everyone finally came to their senses and realized they should be worshiping her. The devil had made an effort to correct this misunderstanding but it was futile as the last anyone saw of that attempt was a very cross Samael marching in the opposite direction with some sort of parchment in hand. No one knows the real story but that's the most believable one we now of.</p>

<h5>Lady Xenosa</h5> <span class="tagline">(The Dominant One)</span><br> <p> - Methodical, calculated, and gorgeous. When a young woman graduates from Harvard law and wonders what her life would have been like if she couldn't have gone to school... Xeno. She could teach Harvard some things though. Back alley Bio-Chem, Guerrilla [warfare] Advertising, and hostage negotiation when someone is standing in Mexico... err, something like that, ask her.  Nothing happens around her that wasn't, to a large degree, engineered. Well, almost nothing *crashing sounds in the background </p>

<h5>Dominik the Madder</h5> <span class="tagline">(Mistress Millie's Mad Hatter)</span><br> <p> - Dominik is a bit of a gear-head, not just figuratively. A childhood accident involving a red hot pinion shot out. He's worn that gear-shaped brand on the side of his face ever since. How do I describe him? You know that one saying,"the lights are on but no one's home?" Well, Someone's home, And the lights do indeed work, just never all at the same time. he's a bit of a brute with a personality that fits like a mascot. Genius with with engines, Mathematics, and... Chemistry?! We still can't figure that one out.</p>

<h5>Mistress Millie Melbourne</h5> <span class="tagline">(The Mistress of Madness)</span><br> <p> - We did our best with this one but lets face it, psychotherapy isn't the type of psychology commonly practiced in a brothel. Mistress Melbourne is twenty (roughly) going on twelve (barely). Her clientele adore her but... I'm not so sure they realize her personality isn't an act... seasoned with a Devil May Care attitude Milly quickly bored by routine. It truly is difficult to see how Xeno and Millie made it this long without any art's and crafts projects comprised of the others' entrails. They may test each other's last nerves but if you have any future plans that involve... Idk, breathing? threatening either of them may result in indefinite postponement of said plans.</p>

<h5>Festus</h5> <span class="tagline">"Waterboy", "Bassist", "go-fer", "Robin" many names for the role</span><br> <p> - He's happily at the bottom of the ladder. But then, who wouldn't be happy at ground level in a brothel? Spoiler: if you don't know why:<span class="inline-spoiler">Imagine being a little boy and looking up with scantily clad women all around you... or better yet, imagine being a boy... no "and..." just that.</span><br> <p> He does what's needed for the girls and is very quiet but respectful. We're not really sure what he gets out of being here. He seems less interested in the girls and more interested in the people coming in... regardless of gender. In the end, it's not like he's on payroll but he's helpful so I guess we get a an extra *clears throat* hand - no pun intended - when we need it and he gets a place to put himself. He can be pretty entertaining to watch though. like an old little kid with a mouse </p>
